version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
      time: '09:30'
      timezone: America/Sao_Paulo
    cooldown:
      default-days: 5
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(actions)
