/**
 * Markdown Reporter
 * Generates a human-readable markdown report from audit results.
 */

function generateMarkdown(result) {
  const { meta, scores, violations, status } = result

  const icon = status === 'pass' ? '✅' : '❌'
  const date = new Date(meta.timestamp).toLocaleString()

  let md = `# ${icon} Quality Gate Report\n\n`
  md += `**Project:** ${meta.project}\n`
  md += `**Commit:** \`${meta.commit}\`\n`
  md += `**Date:** ${date}\n`
  md += `**Preset:** \`${meta.preset}\`\n\n`

  md += `## 📊 Scores\n\n`
  md += `| Category | Score | Status |\n`
  md += `| :--- | :---: | :---: |\n`

  for (const [key, value] of Object.entries(scores)) {
    const s = Math.round(value)
    const icon = s >= 90 ? '🟢' : s >= 50 ? '🟡' : '🔴'
    md += `| ${key} | ${s} | ${icon} |\n`
  }

  md += `\n## 🚨 Violations\n\n`

  if (violations.length === 0) {
    md += `> 🎉 No violations found. Quality is high.\n`
  } else {
    // Group by severity
    const errors = violations.filter(v => v.severity === 'error')
    const warnings = violations.filter(v => v.severity === 'warn')

    if (errors.length > 0) {
      md += `### Errors (${errors.length})\n`
      for (const v of errors) {
        md += `- 🔴 **[${v.area}]** ${v.metric}: \`${v.value}\` (Threshold: \`${v.threshold}\`)\n`
      }
      md += `\n`
    }

    if (warnings.length > 0) {
      md += `### Warnings (${warnings.length})\n`
      for (const v of warnings) {
        md += `- 🟡 **[${v.area}]** ${v.metric}: \`${v.value}\` (Threshold: \`${v.threshold}\`)\n`
      }
    }
  }

  md += `\n---\n*Generated by Quality Core*\n`

  return md
}

const MarkdownReporter = {
  generate: generateMarkdown,
}

module.exports = MarkdownReporter
