name: Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        description: 'Tag a publicar (ex: v1.0.0)'

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: mafhper/github-release-workflows/.github/workflows/release.yml@v1.0.4
    with:
      matrix: '[{"os":"ubuntu-latest"}]'
      tag: ${{ inputs.tag }}
